### ISSUE TITLE
Tracklist unavailable

### ISSUE THREAD

**Issue by Hierrbatnik** [trepDev/mixcloud-with-tracklist#33]
Hi,
Once again tracklist is not displayed, no reaction at all,
Would You please look at it?
cheers
![Screen Shot 01-12-24 at 11 02 PM](https://github.com/trepDev/mixcloud-with-tracklist/assets/145183490/5aab3cfb-2b76-4b4c-91c6-d4537833d8b2)

**Comment by trepDev** [comment]
Hi,
Yes, Mixcloud (once again) made a modification on html/css structure. 
I will check that tomorrow :)
Thx for the issue, I didn't use mixcloud this week. So I didn't know it was broken.

**Comment by trepDev** [comment]
Hi @Hierrbatnik,

The fix is a lot more complicated than I tough.
Mixcloud dynamic display's behavior is becoming increasingly unpredictable.
I am going to stop trying to integrate the playlist directly on the website.
Instead, I will show it in the extension pop-up. Although it will be less practical for users, I have no other option.
On the positive side, it will be more future-proof.

The changes will take some time to implement.
During the week, I will make a new update to notify users about the situation.
By the end of this month, the next working version will be available

**Comment by trepDev** [comment]
Store submission is in progess.
